### ISSUE TITLE
Replace structopts with clap

### ISSUE THREAD

**Issue by KevinGimbel** [KevinGimbel/mktoc#10]
structopts will not receive new features and is integrated with clap, see https://github.com/texitoi/structopt#maintenance

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.

_almost as-is_ makes it seem like this shouldn't be much work.

**Comment by oylenshpeegul** [comment]
Yes, clap's `derive` feature is a pretty easy switch from structopt. Feature `env` is separate as well. It changed a bit more in clap v4, but it's still pretty easy. I'll give this a go.

**Comment by KevinGimbel** [comment]
Thanks a ton! Will be released as part of the 3.1 release!
